name: Add Reviewer to PR

on:
  pull_request:
    types: [opened]

jobs:
  run-on-changelog-branch:
    if: startsWith(github.head_ref, 'changelog/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for assignees and add reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWER: ${{ env.REVIEWER }}
        run: |
          assignees=$(gh pr view ${{ github.event.pull_request.number }} --json assignees -q '.assignees | length')
          if [ "$assignees" -eq 0 ]; then gh pr edit ${{ github.event.pull_request.number }} --add-reviewer ${{ env.REVIEWER }} fi