name: Add Reviewer to PR

on:
  pull_request:
    types: [opened]

jobs:
  run-on-changelog-branch:
    if: startsWith(github.head_ref, 'changelog/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for existing reviews
        id: check-reviews
        uses: octokit/request-action@v3
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add a reviewer if none exist
        if: steps.check-reviews.outputs.data == '[]'
        uses: octokit/request-action@v3
        with:
          route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ env.REVIEWER }}