name: Changelog

on:
  push:
    branches:
      - changelog/**

jobs:
  changelog-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Open PR for changelog update"
          branch: ${{ github.ref }}
          base: main
          title: "Changelog update from ${{ github.ref_name }}"
          body:  |
            This pull request has been automatically created to update the changelog.

            Edit the YYMMDD.mdx file with any updates.
            Committing your changes will trigger the update changelog workflow, which will pull your updates into the main changelog files.

      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.create_pr.outputs.pull_request_number }}
          fetch-depth: 0
  
      - name: Install dependencies
        run: npm install
  
      - name: Run changelog script
        run: npm run changelog
  
      - name: Clean up the mdx files
        run: npm run format-changelog

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update changelog"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set changelog labels
        id: changelog_labels
        run: |
          changed_files=$(git diff --name-only HEAD~1 HEAD)
          labels=()
          for file in $changed_files; do
            case $file in
              'changelog/platform.mdx')
                labels+=('platform')
                ;;
              'changelog/sdks.mdx')
                labels+=('sdks')
                ;;
              'changelog/plugins/highlights.mdx')
                labels+=('plugins')
                ;;
            esac
          done

          labels+=('changelog')
          
          if [ ${#labels[@]} -gt 0 ]; then
            echo "Labels to add: ${labels[@]}"
            gh pr edit "$GITHUB_REF" --add-label "$(IFS=, ; echo "${labels[*]}")"
          else
            echo "No labels to add."
          fi