name: Changelog

on:
  push:
    branches:
      - changelog/**

jobs:
  changelog-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.create_pr.outputs.pull_request_number }}
          fetch-depth: 0
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Run changelog script
        run: npm run changelog

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update changelog"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}