name: Update changelog files

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  run_if:
    if: startsWith(github.event.pull_request.head.ref, 'changelog/')
    runs-on: ubuntu-latest
    steps:
      - name: Print ref
        run: echo "THIS RAN ${{ startsWith(github.event.pull_request.head.ref, 'changelog/') }}"