name: Update changelog files

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  run_if:
    runs-on: ubuntu-latest
    steps:
      - name: Print ref
        run: echo "${{ startsWith(github.event.pull_request.head.ref, 'changelog/') }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print message
        run: echo "this ran"